services:
  db:
    image: mongo:4.1.8-xenial
    container_name: dbmongo
    restart: unless-stopped
    env_file: .env
    environment:
    - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
    - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}

    ports:
      - ${MONGO_PORT_LOCAL}:${MONGO_PORT_DOCKER}
    volumes:
      - dbdata:/data/dbmongo
    networks:
      - crud-network2

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appNodeCrud
    restart: unless-stopped
    env_file: .env
    environment:
      - ${DB_HOST}=db
    ports:
      - ${NODE_PORT_LOCAL}:${NODE_PORT_DOCKER}
    depends_on:
      - db
    volumes:
      - .:/home/app
      - node_modules:/home/app/node_modules
    networks:
      - crud-network2

networks:
    crud-network2:
       driver: bridge

volumes:
    dbdata:
    node_modules:

